application:
  admin-email: "admin@gmail.com"
  admin-password: "admin123"
  jwt-secret: 7390fae56e2d2a3b8f8b773c3a5425dd4203157483590daf2a5ded9f70b22562
  jwt-expiration-time: 86400000

spring:
  application:
    name: OpportuNetRewrite
  datasource:
    url: jdbc:postgresql://localhost:5434/opportunet_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: localhost
      port: 6379
server:
  port: 8080
